<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3585" started-at="2018-06-04T22:02:55Z" finished-at="2018-06-04T22:02:59Z">
    <groups>
      <group name="regression">
        <method signature="AllMethodsPowerONTest.postRequestPowerOn_Valid_range(java.lang.String)[pri:0, instance:lightbulbtest.AllMethodsPowerONTest@6fd02e5]" name="postRequestPowerOn_Valid_range" class="lightbulbtest.AllMethodsPowerONTest"/>
      </group> <!-- regression -->
    </groups>
    <test name="Default test" duration-ms="3585" started-at="2018-06-04T22:02:55Z" finished-at="2018-06-04T22:02:59Z">
      <class name="lightbulbtest.AllMethodsPowerONTest">
        <test-method status="PASS" signature="setupSuite()[pri:0, instance:lightbulbtest.AllMethodsPowerONTest@6fd02e5]" name="setupSuite" is-config="true" duration-ms="36" started-at="2018-06-05T08:02:55Z" finished-at="2018-06-05T08:02:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupSuite -->
        <test-method status="PASS" signature="setup()[pri:0, instance:lightbulbtest.AllMethodsPowerONTest@6fd02e5]" name="setup" is-config="true" duration-ms="1" started-at="2018-06-05T08:02:56Z" finished-at="2018-06-05T08:02:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="postRequestPowerOn_Valid_range(java.lang.String)[pri:0, instance:lightbulbtest.AllMethodsPowerONTest@6fd02e5]" name="postRequestPowerOn_Valid_range" duration-ms="3289" started-at="2018-06-05T08:02:56Z" data-provider="poweron200" finished-at="2018-06-05T08:02:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[20]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at lightbulbtest.AllMethodsPowerONTest.postRequestPowerOn_Valid_range(AllMethodsPowerONTest.java:74)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postRequestPowerOn_Valid_range -->
      </class> <!-- lightbulbtest.AllMethodsPowerONTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
